version: '3.5'

services:

  nginx:
    container_name: "nginx"
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/usr/share/nginx/html/static/media_files
    networks:
      - custom

  web:
    container_name: "web"
    build: ./services/web

    volumes:
      - ./services/web/:/usr/src/app/
      - static_volume:/usr/src/app/project/media/media_files
#      - /services/web/project/media/media_files:/usr/src/app/project/media/media_files
    ports:
      - 1111:1111
    env_file:
      - ./.env.dev
    networks:
      - custom
    depends_on:
      - db


  db:
    container_name: "db"
    image: postgres:13-alpine
    volumes:
      - ./db_dev/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=diplom_project
    env_file:
      - ./.env.dev.db
    ports:
      - '5432:5432'
    networks:
      - custom


volumes:
  static_volume:
    driver: local
  db_dev:
    name: db_dev

networks:
  custom:
    driver: bridge