name: Run Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Set up Python 3.10.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.10
    - name: Install dependencies
      run: |
        make install
    - name: Test
      run: |
        make test
    - name: Black
      run: |
        make black
    - name: Isort
      run: |
        make isort
    - name: Flake8
      run: |
        make flake8

