name: Run Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Set up Python 3.10.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.10
    - name: Install dependencies
      run: |
        make install
    - name: Black
      run: |
        make black
    - name: Create_db
      run: |
        make create_db
    - name: Test
      run: |
        make test

#    - name: Isort
#      run: |
#        make isort
#    - name: Flake8
#      run: |
#        make flake8

#    - name: Mypy
#      run: |
#        make mypy
